{"timestamp":"2025-07-11T22:26:50.379688","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-11T22:26:50.379974","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/bank_etl_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-11T22:26:50.407947Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T22:26:50.409159Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T22:26:50.409233Z","level":"info","event":"Current task name:extract_transform_load","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T22:26:50.409295Z","level":"info","event":"Dag name:bank_data_etl_process","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T22:26:50.411561","level":"info","event":"Connection Retrieved 'postgres_bank_ds'","logger":"airflow.hooks.base"}
{"timestamp":"2025-07-11T22:26:50.412087","level":"info","event":"===== Обработка файла /opt/airflow/dags/data/md_account_d.csv для таблицы MD_ACCOUNT_D с кодировкой cp1251 =====","logger":"root"}
{"timestamp":"2025-07-11T22:26:50.418769","level":"warning","event":"/opt/airflow/dags/bank_etl_dag.py:71: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.\n  df[col] = pd.to_datetime(df[col], dayfirst=True, errors='coerce')\n","logger":"py.warnings"}
{"timestamp":"2025-07-11T22:26:50.465910","level":"info","event":"===== Обработка файла /opt/airflow/dags/data/md_currency_d.csv для таблицы MD_CURRENCY_D с кодировкой koi8-r =====","logger":"root"}
{"timestamp":"2025-07-11T22:26:50.469007","level":"warning","event":"/opt/airflow/dags/bank_etl_dag.py:71: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.\n  df[col] = pd.to_datetime(df[col], dayfirst=True, errors='coerce')\n","logger":"py.warnings"}
{"timestamp":"2025-07-11T22:26:50.482488","level":"info","event":"===== Обработка файла /opt/airflow/dags/data/md_exchange_rate_d.csv для таблицы MD_EXCHANGE_RATE_D с кодировкой cp1251 =====","logger":"root"}
{"timestamp":"2025-07-11T22:26:50.484692","level":"warning","event":"/opt/airflow/dags/bank_etl_dag.py:71: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.\n  df[col] = pd.to_datetime(df[col], dayfirst=True, errors='coerce')\n","logger":"py.warnings"}
{"timestamp":"2025-07-11T22:26:50.500262","level":"info","event":"===== Обработка файла /opt/airflow/dags/data/md_ledger_account_s.csv для таблицы MD_LEDGER_ACCOUNT_S с кодировкой koi8-r =====","logger":"root"}
{"timestamp":"2025-07-11T22:26:50.501928","level":"warning","event":"/opt/airflow/dags/bank_etl_dag.py:71: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.\n  df[col] = pd.to_datetime(df[col], dayfirst=True, errors='coerce')\n","logger":"py.warnings"}
{"timestamp":"2025-07-11T22:26:50.513631","level":"error","event":"ОШИБКА ВНУТРИ ETL ЗАДАЧИ: (psycopg2.errors.UndefinedColumn) column \"ledger1_account\" of relation \"MD_LEDGER_ACCOUNT_S\" does not exist\nLINE 1: ...ction_number\", \"section_name\", \"subsection_name\", \"ledger1_a...\n                                                             ^\n\n[SQL: INSERT INTO \"DS\".\"MD_LEDGER_ACCOUNT_S\" (\"chapter\", \"chapter_name\", \"section_number\", \"section_name\", \"subsection_name\", \"ledger1_account\", \"ledger1_account_name\", \"ledger_account\", \"ledger_account_name\", \"characteristic\", \"start_date\", \"end_date\") SELECT \"chapter\", \"chapter_name\", \"section_number\", \"section_name\", \"subsection_name\", \"ledger1_account\", \"ledger1_account_name\", \"ledger_account\", \"ledger_account_name\", \"characteristic\", \"start_date\", \"end_date\" FROM \"DS\".\"temp_md_ledger_account_s\" ON CONFLICT (\"ledger_account\", \"start_date\") DO UPDATE SET \"chapter\" = EXCLUDED.\"chapter\", \"chapter_name\" = EXCLUDED.\"chapter_name\", \"section_number\" = EXCLUDED.\"section_number\", \"section_name\" = EXCLUDED.\"section_name\", \"subsection_name\" = EXCLUDED.\"subsection_name\", \"ledger1_account\" = EXCLUDED.\"ledger1_account\", \"ledger1_account_name\" = EXCLUDED.\"ledger1_account_name\", \"ledger_account_name\" = EXCLUDED.\"ledger_account_name\", \"characteristic\" = EXCLUDED.\"characteristic\", \"end_date\" = EXCLUDED.\"end_date\";]\n(Background on this error at: https://sqlalche.me/e/14/f405)","logger":"root"}
{"timestamp":"2025-07-11T22:26:50.513757","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"AirflowFailException","exc_value":"ETL процесс провалился с ошибкой: (psycopg2.errors.UndefinedColumn) column \"ledger1_account\" of relation \"MD_LEDGER_ACCOUNT_S\" does not exist\nLINE 1: ...ction_number\", \"section_name\", \"subsection_name\", \"ledger1_a...\n                                                             ^\n\n[SQL: INSERT INTO \"DS\".\"MD_LEDGER_ACCOUNT_S\" (\"chapter\", \"chapter_name\", \"section_number\", \"section_name\", \"subsection_name\", \"ledger1_account\", \"ledger1_account_name\", \"ledger_account\", \"ledger_account_name\", \"characteristic\", \"start_date\", \"end_date\") SELECT \"chapter\", \"chapter_name\", \"section_number\", \"section_name\", \"subsection_name\", \"ledger1_account\", \"ledger1_account_name\", \"ledger_account\", \"ledger_account_name\", \"characteristic\", \"start_date\", \"end_date\" FROM \"DS\".\"temp_md_ledger_account_s\" ON CONFLICT (\"ledger_account\", \"start_date\") DO UPDATE SET \"chapter\" = EXCLUDED.\"chapter\", \"chapter_name\" = EXCLUDED.\"chapter_name\", \"section_number\" = EXCLUDED.\"section_number\", \"section_name\" = EXCLUDED.\"section_name\", \"subsection_name\" = EXCLUDED.\"subsection_name\", \"ledger1_account\" = EXCLUDED.\"ledger1_account\", \"ledger1_account_name\" = EXCLUDED.\"ledger1_account_name\", \"ledger_account_name\" = EXCLUDED.\"ledger_account_name\", \"characteristic\" = EXCLUDED.\"characteristic\", \"end_date\" = EXCLUDED.\"end_date\";]\n(Background on this error at: https://sqlalche.me/e/14/f405)","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":867,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1159,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/decorator.py","lineno":251,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/bank_etl_dag.py","lineno":103,"name":"extract_transform_load"}],"is_group":false,"exceptions":[]},{"exc_type":"ProgrammingError","exc_value":"(psycopg2.errors.UndefinedColumn) column \"ledger1_account\" of relation \"MD_LEDGER_ACCOUNT_S\" does not exist\nLINE 1: ...ction_number\", \"section_name\", \"subsection_name\", \"ledger1_a...\n                                                             ^\n\n[SQL: INSERT INTO \"DS\".\"MD_LEDGER_ACCOUNT_S\" (\"chapter\", \"chapter_name\", \"section_number\", \"section_name\", \"subsection_name\", \"ledger1_account\", \"ledger1_account_name\", \"ledger_account\", \"ledger_account_name\", \"characteristic\", \"start_date\", \"end_date\") SELECT \"chapter\", \"chapter_name\", \"section_number\", \"section_name\", \"subsection_name\", \"ledger1_account\", \"ledger1_account_name\", \"ledger_account\", \"ledger_account_name\", \"characteristic\", \"start_date\", \"end_date\" FROM \"DS\".\"temp_md_ledger_account_s\" ON CONFLICT (\"ledger_account\", \"start_date\") DO UPDATE SET \"chapter\" = EXCLUDED.\"chapter\", \"chapter_name\" = EXCLUDED.\"chapter_name\", \"section_number\" = EXCLUDED.\"section_number\", \"section_name\" = EXCLUDED.\"section_name\", \"subsection_name\" = EXCLUDED.\"subsection_name\", \"ledger1_account\" = EXCLUDED.\"ledger1_account\", \"ledger1_account_name\" = EXCLUDED.\"ledger1_account_name\", \"ledger_account_name\" = EXCLUDED.\"ledger_account_name\", \"characteristic\" = EXCLUDED.\"characteristic\", \"end_date\" = EXCLUDED.\"end_date\";]\n(Background on this error at: https://sqlalche.me/e/14/f405)","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/opt/airflow/dags/bank_etl_dag.py","lineno":96,"name":"extract_transform_load"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1385,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py","lineno":334,"name":"_execute_on_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1577,"name":"_execute_clauseelement"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1953,"name":"_execute_context"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":2134,"name":"_handle_dbapi_exception"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py","lineno":211,"name":"raise_"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1910,"name":"_execute_context"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py","lineno":736,"name":"do_execute"}],"is_group":false,"exceptions":[]},{"exc_type":"UndefinedColumn","exc_value":"column \"ledger1_account\" of relation \"MD_LEDGER_ACCOUNT_S\" does not exist\nLINE 1: ...ction_number\", \"section_name\", \"subsection_name\", \"ledger1_a...\n                                                             ^\n","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py","lineno":1910,"name":"_execute_context"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py","lineno":736,"name":"do_execute"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-07-11T22:26:50.517384Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T22:26:50.517440Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T22:26:50.517484Z","level":"info","event":"Task:<Task(_PythonDecoratedOperator): extract_transform_load>","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T22:26:50.517533Z","level":"info","event":"Failure caused by ETL процесс провалился с ошибкой: (psycopg2.errors.UndefinedColumn) column \"ledger1_account\" of relation \"MD_LEDGER_ACCOUNT_S\" does not exist","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T22:26:50.517578Z","level":"info","event":"LINE 1: ...ction_number\", \"section_name\", \"subsection_name\", \"ledger1_a...","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T22:26:50.517620Z","level":"info","event":"                                                             ^","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T22:26:50.517691Z","level":"info","event":"","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T22:26:50.517733Z","level":"info","event":"[SQL: INSERT INTO \"DS\".\"MD_LEDGER_ACCOUNT_S\" (\"chapter\", \"chapter_name\", \"section_number\", \"section_name\", \"subsection_name\", \"ledger1_account\", \"ledger1_account_name\", \"ledger_account\", \"ledger_account_name\", \"characteristic\", \"start_date\", \"end_date\") SELECT \"chapter\", \"chapter_name\", \"section_number\", \"section_name\", \"subsection_name\", \"ledger1_account\", \"ledger1_account_name\", \"ledger_account\", \"ledger_account_name\", \"characteristic\", \"start_date\", \"end_date\" FROM \"DS\".\"temp_md_ledger_account_s\" ON CONFLICT (\"ledger_account\", \"start_date\") DO UPDATE SET \"chapter\" = EXCLUDED.\"chapter\", \"chapter_name\" = EXCLUDED.\"chapter_name\", \"section_number\" = EXCLUDED.\"section_number\", \"section_name\" = EXCLUDED.\"section_name\", \"subsection_name\" = EXCLUDED.\"subsection_name\", \"ledger1_account\" = EXCLUDED.\"ledger1_account\", \"ledger1_account_name\" = EXCLUDED.\"ledger1_account_name\", \"ledger_account_name\" = EXCLUDED.\"ledger_account_name\", \"characteristic\" = EXCLUDED.\"characteristic\", \"end_date\" = EXCLUDED.\"end_date\";]","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-11T22:26:50.517780Z","level":"info","event":"(Background on this error at: https://sqlalche.me/e/14/f405)","chan":"stdout","logger":"task"}
